### ISSUE TITLE
Documentation about adding and removing fields

### ISSUE THREAD

**Issue by tpra** [eduardoarandah/UserManager#11]
I'm confused by the end of the Readme.md :

> Now you can remove the package with composer
> composer require backpack/usermanager

Why would a "composer require" on another (unexisting it seems) package remove yours ?
What about UserStoreCrudRequest and UserUpdateCrudRequest if the package is removed ?

**Comment by eduardoarandah** [comment]
jeje it should have said "composer remove" 
you're right, requests are missing!

**Comment by eduardoarandah** [comment]
I Improved documentation to make it easier to extend your own controller: https://github.com/eduardoarandah/UserManager/blob/master/README.md
