### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by tabacitu** [eduardoarandah/UserManager#3]
I see the ```composer.json``` file says it's under an MIT license but there's no license file included. It's best-practice to have one inside the project - Github will even feature it then.

Would you like me to create a PR that adds it?

Cheers!

**Comment by eduardoarandah** [comment]
thanks! didn't know that. 

https://github.com/eduardoarandah/UserManager/commit/b83ebf8b3a88c79d70421c600cb60c7ab868b107
