### ISSUE TITLE
[Feature req] Use Backpack\Base user model instead of App one

### ISSUE THREAD

**Issue by tabacitu** [eduardoarandah/UserManager#5]
I see you've inserted instructions on using the CrudTrait on the User model. Since Backpack 3.4, Base includes a User model itself, which can be configured in the base config file:
```php
    // Fully qualified namespace of the User model
    'user_model_fqn' => \Backpack\Base\app\Models\BackpackUser::class,
```

I suggest we use that one. I can submit a PR if you'd like. I think this would:
- make it one less step to install UserManager (one-line-install, actually);
- make UserManager use the same User model as Base (authentication, etc), which is more intuitive, I think;

What do you think?

Cheers!

**Comment by eduardoarandah** [comment]
About that.. 

I see **BackpackUser** extends **App\User** which extends **Illuminate\Foundation\Auth\User**

Lets say a controller wants to use the user model. 
It would go like this:

![model1](https://user-images.githubusercontent.com/4065733/40926014-cbcbadc4-67e0-11e8-8998-b4b54613eca3.png)

**We are leaving user domain to go back again, and then go out again**

This gives us a consequence: User Model and table name become hard-coded inside the package. 

What if we want user model in App\Models\User and table name singular "user" ?

![File vendor/backpack/base/src/app/Models/BackpackUser.php](https://user-images.githubusercontent.com/4065733/40926197-45a04948-67e1-11e8-98e3-7e1e9043e1dc.png)



## Why not doing something like this?

![model2](https://user-images.githubusercontent.com/4065733/40926126-12268492-67e1-11e8-9280-03bbda5c1775.png)

## BackpackUser
```PHP
<?php
namespace Backpack\Base\app\Models;

use Backpack\Base\app\Notifications\ResetPasswordNotification as ResetPasswordNotification;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Backpack\CRUD\CrudTrait; 

class BackpackUser extends Authenticatable
{
    use CrudTrait;   

    public function sendPasswordResetNotification($token) {
        $this->notify(new ResetPasswordNotification($token));
    }

    public function toMail($notifiable) {
        return (new MailMessage())
            ->line([
                trans('backpack.base.password_reset.line_1'),
                trans('backpack.base.password_reset.line_2'),
            ])
            ->action(trans('backpack.base.password_reset.button'), url(config('backpack.base.route_prefix').'/password/reset', $this->token))
            ->line(trans('backpack.base.password_reset.notice'));
    }
}

```

## App\User

```PHP
<?php
namespace App;

use Illuminate\Notifications\Notifiable;
use  Backpack\Base\app\Models\BackpackUser as BackpackUser;

class User extends BackpackUser
{
    use Notifiable;
    protected $table = 'users';

    protected $fillable = [
        'name', 'email', 'password',
    ];
   
    protected $hidden = [
        'password', 'remember_token',
    ];
}

```

This leaves the programmer free to move User model to App\Models\User
and change table name

**Comment by tabacitu** [comment]
Fair point. I'm not happy with having the App domain mentioned in BackpackUser either. But I honestly didn't see another way we could eliminate "_modify your User model like so_" as an installation step in Base. 

### Option A

Let's call the convoluted thing we have right now **(```Backpack\Base\app\Models\BackpackUser extends User```) Option A**.

### Option B

If we were to go back to asking the user to modify his User model upon Base installation, I think I'd rather have a Trait, than a BackpackUser to extend. So far we've avoided having a BackpackUser class to extend, because some Auth packages require you to extend their User model, and we didn't want to be incompatible with them. But **we _could_ easily have a Trait with our User stuff in it** - say... ```CanResetPasswordByEmail```. That's all we _need_ anyway. Let's call this **Option B**. So we can totally do something like this:

```php
<?php

namespace Backpack\Base\Models\Traits;

use Backpack\Base\app\Notifications\ResetPasswordNotification as ResetPasswordNotification;

trait CanResetPasswordByEmail
{
    public function sendPasswordResetNotification($token) {
        $this->notify(new ResetPasswordNotification($token));
    }

    public function toMail($notifiable) {
        return (new MailMessage())
            ->line([
                trans('backpack.base.password_reset.line_1'),
                trans('backpack.base.password_reset.line_2'),
            ])
            ->action(trans('backpack.base.password_reset.button'), url(config('backpack.base.route_prefix').'/password/reset', $this->token))
            ->line(trans('backpack.base.password_reset.notice'));
    }
}
```
then:
```diff
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
+use Backpack\Base\Models\Traits\CanResetPasswordByEmail;
+use Backpack\CRUD\CrudTrait;

class User extends Authenticatable
{
    use Notifiable;
+  use CrudTrait;
+  use CanResetPasswordByEmail;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

```

I think this is the same thing you suggested, but a little less invasive, since it allow the User model to extend something else, if needed. 

But it suffers from the same problem. The problem with using either extend or a trait is that _it cannot be done automatically_. It would add an extra step to installing Base - it can't just be ```php artisan backpack:base:install```. And I really _really_ think all Backpack packages should be installable with one command. Otherwise we'll never be able to quickly install all Backpack packages you need with one copy-paste. We'll never be able to have an "App Store" for Backpack packages. It's a huge constraint, to do things automatically, I know. But I think it's the future.

I don't know... difficult decision this one. 

### Option C

Alternatively (**option C**) would be to automatically make the modifications needed in Option B to the User model. We could, upon Base installation:
- try to figure out where the User model is [maybe by looking in ```config('auth.providers')```, the first entry, maybe some other way?];
- ask the developer if that's his User model (```What is your User model?``` Prepopulated answer: ```App\User::class```); 
- then proceed and make the modifications we need to the User class, in code, automatically;

But automatically modifying code in PHP is, as far as I know, hit and miss. And... it feels very dirty to me, I don't know why. **What do you think about this option?**

### Option D

Instead of having a BackpackUser class inside the Backpack\Base package, we could publish it in the Models folder, upon installation. This would:
- allow the developer to change the location of his User model (but it needs to be done before running ```backpack:base:install```;
- allow the developer to _easily_ make any modifications he wants to BackpackUser [ex: put a global scope ```where(admin, true)``` or something like that];
- allow us to use that model as ```config('backpack.base.user_model_fqn')```, both in authentication and in packages like UserManager;
- make it intuitive for the developer - "_ok, so now I have this new model in the Models folder, this model must be used everywhere by Backpack_";
- allow us to NOT edit an existing class code (User);
- BUT ```BackpackUser extends User```, so we'd _still_ need to figure out what the User model is, and type it in this generated Model; so I think there's still room for failure; but at least it's our Model, not the developer's; 

I don't know... I feel slightly better about this than Option C, but... still not happy with it for some reason... What do you think?

---

I'll keep thinking about this, maybe I figure out a better way. Sorry for the long post, it's something that I think is super-important, and I wanted to get every possible option on paper, to see how they look and get feedback.

**Comment by eduardoarandah** [comment]
mm.. aren't these two functions are doing the same thing?
```
function sendPasswordResetNotification()
function toMail()
```
the code in function toMail() I think should go inside sendPasswordResetNotification class. 
Or maybe I'm missing something

**Comment by eduardoarandah** [comment]
Idea: 
Why not call another function instead of overwriting sendPasswordResetNotification ? 

That way we: 
- not longer modify user model
- don't mess with built-in auth, both could live in harmony, front-end auth and backend-auth

I'm not sure if this is easy, never done it before. 

It may involve creating a new password broker?

- Extend `laravel\framework\src\Illuminate\Auth\Passwords\PasswordBroker.php`
- In that file there's a trait `Illuminate\Contracts\Auth\CanResetPassword` with the original call to function `ResetPasswordNotification`
- Change to BackpackResetPasswordNotification
- Make Backpack Auth Controllers use that broker [Password Broker Customization](https://laravel.com/docs/5.6/passwords#password-customization)

**Comment by eduardoarandah** [comment]
**Option A**

Well.. I think this option crossed the line of "irreductible complexity" 
If the programmer wants to move User.php to Models\User.php then he has to... 
.. mmm... I don't know... is it possible?

**Option B**

Adding "CrudTrait" to User.php is done routinely to every model. 
Minimally invasive, nothing new to learn, **I like it**

`sendPasswordResetNotification`
This one modifies built-in Authentication. 
I don't like it. 
There should be a way of using something like `sendBackpackPasswordResetNotification`

**Option C**
I don't like it. 
Must never change code in programmer's land

**Option D**
The programmer is supposed to extend package code, not the other way around, feels like an anti-pattern. 

User model is a VIP citizen in programmer's land, no package should change it without warning.
My vote goes for the old method... asking the programmer to modify it by hand. 

**Option E** 
publishes User Model

```
$ php artisan backpack:user-model --folder=Models * optional
$ warning: user model will be renamed User.php.backup read docs here....
``` 



With Option E we have more commands, but the parts that mess into _programmer's land_ are optional.

**Comment by tabacitu** [comment]
Pff... I think you're right... I don't like any option either. But I don't like the old way either, because it's not automatic...

Let me think about it some more... maybe I come up with something, I don't know. 

---

But I think we may have gotten to a point where Auth is more complicated than it should be. By default:
- we ARE using Laravel's ```users``` table
- we ARE using Laravel's ```User``` model
- we ARE NOT using Laravel's the Auth Controllers
- we ARE NOT using Laravel's auth views
- we ARE using Laravel's guard and password broker

I think bit by bit we've made this more complicated than it should be. I know, that's what happens when you keep adding features, it's not my first tango :-) But I'm not very happy with it. It doesn't seem clean to me anymore, it's more difficult to understand. **Maybe we should separate the Backpack auth entirely?** Different model, different table (maybe), different guard and different broker? At least then it would be clear and easy to understand: _Backpack's auth is Backpack's auth. Laravel's auth is Laravel's auth. The only thing they have in common is the ```users``` table, because admins are users._ I don't know... I'm not hellbent on this, but it does sound simpler to me at the moment...

**Comment by tabacitu** [comment]
@OwenMelbz @AbbyJanke @OliverZiegler @b8ne @lloy0076 @indra1 what do you think? Long thread, I know, I understand if you don't have time to read it, but if you do, maybe one of you could have an idea to take us out of this jam.

**Comment by OwenMelbz** [comment]
Sorry if this is not much help :D

But I personally didn't even notice the BackpackUser model - I just manually added the 2 functions like normal into it during the install.

# IF this is about adding default functionality to users for ease of installation

I would think the most "typical" method would just to be add a trait, this is normal throughout laravel packages.

Although - You could use laravels Macro system - lookup which model is defined in the `config/auth.php` which will be something like

```php
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\Models\User::class,
        ],
```

Then use the macro system to add your custom methods to the class.

Another one - which might be a bit more restrictive, you could utilise the IoC container, whenever an instance of the users defined model is requested, you actually return a decorated version which has the custom functionality on.

---

So those are some other ideas  - of course I might not be understanding/reading the original issue :D

**Comment by lloy0076** [comment]
Option E: Why do we need to provide authentication that is so general it works for everyone?

Provide one option and then advice on how to deviate from it.

The above seems to be what Laravel itself does.

**Comment by eduardoarandah** [comment]
**Option F: Simple instead of complex**

Facts:
- _Built-in auth and Backpack-auth do the same thing._ 
- _AdminLte login screens are not beautiful_

Why not use built-in authentication?

in config/backpack/base.php do this.
```
'middleware_class' => [
        \Illuminate\Auth\Middleware\Authenticate::class,
    ],
```
works the same

Want different views?

`php artisan backpack:auth-views`

Advantages:

- Questions about auth to Taylor Otwell, less things to support
- Design a nicer login screen

**Comment by tabacitu** [comment]
@eduardoarandah , I'm finally getting to tackle this issue in this week's planned launch (Base 0.9.x to Base 1.0.0). 

About **Option F**:
- Backpack auth and Laravel auth do _exactly_ the same thing; but we _do_ need to edit it a little bit, to direct the user to the ```admin``` domain/prefix once logged in; so _some_ editing is mandatory, we can't just use the default Laravel login;
- I agree, AdminLTE login screens are NOT beautiful; neither are Laravel's, in my opinion; but I've [worked on this](https://github.com/Laravel-Backpack/Base/pull/330), and I think Backpack's login screens _will_ be beautiful :-)

![screenshot 2018-11-08 at 05 54 16](https://user-images.githubusercontent.com/1032474/48177081-a7954580-e31b-11e8-9043-35203a45631d.png)
![screenshot 2018-11-08 at 05 54 41](https://user-images.githubusercontent.com/1032474/48177082-a7954580-e31b-11e8-9611-7c02c06cdca3.png)
![screenshot 2018-11-08 at 05 54 26](https://user-images.githubusercontent.com/1032474/48177083-a7954580-e31b-11e8-8c06-a58722856efb.png)

**Comment by tabacitu** [comment]
Since in [the soon-to-be-released Base](https://github.com/Laravel-Backpack/Base/pull/324) update, by default Backpack:
- uses our custom ```backpack``` guard
- uses our custom ```backpack``` password broker
- uses our custom ```backpack``` auth provider
- uses a separate session [I know @OwenMelbz will be happy about that :-) ]

Which in turn:
- use our custom ```AuthController```
- use our custom auth routes (under the ```admin``` or custom prefix)
- use our custom ```Backpack\Base\app\BackpackUser``` model

I think things are much _much_ cleaner now. The only thing our auth has in common with Laravel's is the ```App\User``` model - because ```Backpack\Base\app\BackpackUser extends App\User```.


**The only thing I don't like about the new system is that:**
1) If the developer changes the location of ```App\User``` to ```App\Models\User``` (as many do), they also need to 
   - create ```App\Models\BackpackUser.php```;
   - copy-paste the contents of BackpackUser, but make sure it extends ```App\Models\User```;
   - change the user model inside ```config/backpack/base.php```;
2) like @eduardoarandah said [here](https://github.com/eduardoarandah/UserManager/issues/5#issuecomment-394400798), we go from Vendor to App then to Vendor again: ```Backpack\Base\app\BackpackUser extends App\User``` then ```App\User extends Illuminate\Foundation\Auth\User```;

Because of the above, I think a good idea would be to implement **Option D**:

> Instead of having a ```BackpackUser``` class inside the Backpack\Base package, we could publish it in the Models folder, upon installation. This would:
>
> - allow the developer to change the location of his User model (but it needs to be done before running ```backpack:base:install```;
> - allow the developer to easily make any modifications he wants to BackpackUser [ex: put a global scope ```where(admin, true)``` or something like that];
> - allow us to use that model as ```config('backpack.base.user_model_fqn')```, both in authentication and in packages like UserManager;
> - make it intuitive for the developer - "_ok, so now I have this new model in the Models folder, this model must be used everywhere by Backpack_";
> - allow us to NOT edit an existing class code (User);
>
> BUT BackpackUser extends User, so we'd still need to figure out what the User model is, and type it in this generated Model; so I think there's still room for failure; but at least it's our Model, not the developer's;

I no longer think we should try to determine the User model though. I think we can just write in the console: ```App\Models\BackpackUser has been published and extends App\User; If you've moved your User model, please adjust your App\Models\BackpackUser accordingly```. And that's it. 

I'll create a PR for this soon. I think we've ended up with a wonderful solution, perfectly usable for most installs, but super-easy to customize :-)  **What do you guys think? Anything I missed?**

**Comment by tabacitu** [comment]
BOOM! Here it is: https://github.com/Laravel-Backpack/Base/pull/334 :-)

**Comment by eduardoarandah** [comment]
hey @tabacitu !

I changed the default user model in this package:
https://github.com/eduardoarandah/UserManager/blob/master/src/config/eduardoarandah/usermanager.php

**Comment by tabacitu** [comment]
Looks good to me @eduardoarandah ! That model will be there for all Backpack v4 installations. And since it's a config option, if it's not there, people can change it.
